coursedata = read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", stringsAsFactors = FALSE)
coursedataToUse <- subset(coursedata, ((as.Date(Date, "%d/%m/%Y") >= "2007-2-1") & (as.Date(Date, "%d/%m/%Y") <= "2007-2-2")))
timeseries <- ts(coursedataToUse$Global_active_power)
plot.ts(timeseries, yax.flip = TRUE, xlab = "", ylab = "Global Active Power (kilowatts)")
#axis(side = 1, at = as.Date(coursedataToUse$Date, '%b-%y'), labels = as.Date(coursedataToUse$Date, '%b-%y'))
dev.copy(png,'plot2.png')
dev.off()